# Generated by Django 3.0.4 on 2020-04-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_athlete_id', models.IntegerField(unique=True)),
                ('strava_athlete_name', models.CharField(max_length=255)),
                ('srodunia_athlete_name', models.CharField(max_length=255, null=True)),
                ('athlete_avatar_img_url', models.URLField()),
                ('role', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_segment_id', models.IntegerField(unique=True)),
                ('strava_segment_name', models.CharField(max_length=255)),
                ('srodunia_segment_type', models.CharField(blank=True, choices=[], max_length=255)),
                ('srodunia_segment_cat', models.CharField(blank=True, choices=[], max_length=255)),
                ('srodunia_segment_zone', models.CharField(blank=True, choices=[], max_length=255)),
                ('srodunia_segment_section', models.CharField(blank=True, choices=[], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StravaClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(unique=True)),
                ('club_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StravaSegmentLeaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('strava_activity_id', models.IntegerField()),
                ('strava_effort_id', models.IntegerField(unique=True)),
                ('rank', models.IntegerField()),
                ('effort_date', models.DateField()),
                ('avg_speed', models.CharField(max_length=32)),
                ('avg_hr', models.CharField(max_length=32, null=True)),
                ('avg_power', models.CharField(max_length=32, null=True)),
                ('vam', models.CharField(max_length=32, null=True)),
                ('time_result', models.TimeField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.StravaClubs')),
                ('strava_athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.AthleteDetails')),
                ('strava_segement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.SegmentDescription')),
            ],
        ),
    ]
