# Generated by Django 3.0.4 on 2020-04-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_athletedetails_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentdescription',
            name='average_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='climb_category',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='end_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='end_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='maximum_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='star_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='start_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='start_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='strava_effort_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='segmentdescription',
            name='total_elevation_gain',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segmentdescription',
            name='srodunia_segment_cat',
            field=models.CharField(choices=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segmentdescription',
            name='srodunia_segment_section',
            field=models.CharField(choices=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segmentdescription',
            name='srodunia_segment_type',
            field=models.CharField(choices=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segmentdescription',
            name='srodunia_segment_zone',
            field=models.CharField(choices=[], max_length=255, null=True),
        ),
    ]
