# Generated by Django 3.0.4 on 2020-04-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200404_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravasegmentleaderboard',
            name='leaderboard_unique_week_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
