# Generated by Django 3.0.4 on 2020-04-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20200409_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravasegmentleaderboard',
            name='time_result',
            field=models.CharField(max_length=10),
        ),
    ]
