# Generated by Django 3.0.4 on 2020-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20200409_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravasegmentleaderboard',
            name='time_filter',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
