# Generated by Django 3.0.4 on 2020-04-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_stravasegmentleaderboard_time_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravasegmentleaderboard',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
