# Generated by Django 3.0.4 on 2020-04-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_stravasegmentleaderboard_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravasegmentleaderboard',
            name='week_number',
            field=models.IntegerField(null=True),
        ),
    ]
