# Generated by Django 3.0.4 on 2020-04-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_stravasegmentleaderboard_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentdescription',
            name='srodunia_segment_cat',
            field=models.CharField(choices=[('-1', 'DH: < 0%'), ('0', 'FLAT: 0 - 4%'), ('1', 'ROLL: 4 - 8%'), ('2', 'HILL: 8 - 12%'), ('3', 'CLIMB: > 12%')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segmentdescription',
            name='srodunia_segment_section',
            field=models.CharField(choices=[('NW', 'PN-ZACH'), ('NE', 'PN-WSCH'), ('SW', 'PD-ZACH'), ('SE', 'PD-WSCH')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segmentdescription',
            name='srodunia_segment_type',
            field=models.CharField(choices=[('1', '1 - 4 minuty'), ('5', '5 - 15 minut'), ('20', '16 - 44 minut'), ('60', '45 - 110 minut'), ('110', 'powyżej 110 minut')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segmentdescription',
            name='srodunia_segment_zone',
            field=models.CharField(choices=[('5', 'MAX 5 Pkt'), ('6', 'MAX 6 Pkt'), ('7', 'MAX 7 Pkt')], max_length=255, null=True),
        ),
    ]
