# Generated by Django 3.0.4 on 2020-04-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20200411_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletedetails',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='segmentdescription',
            name='srodunia_segment_section',
            field=models.CharField(choices=[('NW', '↖️ PN-ZACH'), ('NE', 'PN-WSCH ↗️'), ('SW', '↙️ PD-ZACH'), ('SE', 'PD-WSCH ↘️')], max_length=255, null=True),
        ),
    ]
