# Generated by Django 3.0.4 on 2020-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_auto_20200412_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentdescription',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
