# Generated by Django 3.0.4 on 2020-04-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_segmentdescription_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravasegmentleaderboard',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
