# Generated by Django 3.0.4 on 2020-04-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_stravasegmentleaderboard_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravasegmentleaderboard',
            name='strava_effort_id',
            field=models.CharField(max_length=255),
        ),
    ]
