# Generated by Django 3.0.4 on 2020-03-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StravaSummaryClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_club_id', models.IntegerField()),
                ('club_name', models.CharField(max_length=128)),
                ('profile_photo_md', models.URLField(null=True)),
                ('profile_photo', models.URLField(null=True)),
                ('club_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StravaDetailedAthlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.IntegerField()),
                ('username', models.CharField(max_length=128)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('profile_photo_md', models.URLField(null=True)),
                ('profile_photo', models.URLField(null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('strava_summit', models.BooleanField(default=False)),
                ('ftp', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('clubs', models.ManyToManyField(to='srodunia.StravaSummaryClub')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('strava_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='srodunia.StravaDetailedAthlete')),
            ],
        ),
    ]
